// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase Web App Configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOaRCFiH--lrTQgaTdh-6HyqM0_DY2DB4',
    appId: '1:189603872814:web:65708c604ad6e9ee1ddfbf',
    messagingSenderId: '189603872814',
    projectId: 'garasifyy',
    authDomain: 'garasifyy.firebaseapp.com',
    storageBucket: 'garasifyy.firebasestorage.app',
    measurementId: 'G-JH69VW685Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOaRCFiH--lrTQgaTdh-6HyqM0_DY2DB4', // Try using Web Key
    appId: 'REPLACE_WITH_YOUR_ANDROID_APP_ID',
    messagingSenderId: '189603872814',
    projectId: 'garasifyy',
    storageBucket: 'garasifyy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_IOS_API_KEY',
    appId: 'REPLACE_WITH_YOUR_IOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId: 'garasifyy-mobile-demo',
    storageBucket: 'garasifyy-mobile-demo.appspot.com',
    iosClientId: 'REPLACE_WITH_YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.garasifyyMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_MACOS_API_KEY',
    appId: 'REPLACE_WITH_YOUR_MACOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId: 'garasifyy-mobile-demo',
    storageBucket: 'garasifyy-mobile-demo.appspot.com',
    iosClientId: 'REPLACE_WITH_YOUR_MACOS_CLIENT_ID',
    iosBundleId: 'com.example.garasifyyMobile',
  );
}
